print ("Twinkle, twinkle, little star,")
print ("\tHow I wonder what you are!")
print ("\t        Up above the wolrd so high,", "\n\t        Like a dimond in the sky.")
print("Twinkle, twinkle, little star,","\n\tHow I wonder what you are!", end="\n\n\n")
#ex.2)
print(""""Hello Python world, where "\ n", is used for moving new line and "\ t" is used for a tab " """, end="\n\n\n")
#ex.3)
print("          CV", end="\n\n")
print("Name\n\tNune")
print("Surename\n\tMkrtchyan")
print("Education\n\t2010-16` mastert's degree in banking organization")
print("work experiance\n\t2016-18` CARD AgroCredit UCO CJSC-loan officer\n\t2018 till today` ACBA BANK OGSC-retail business consultant")